package com.aliproinv.gastos;

import android.app.*;
import android.os.Bundle;
import android.content.*;
import android.database.Cursor;
import android.database.sqlite.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
  static final int TEXT=Color.rgb(17,24,39), MUTED=Color.rgb(107,114,128), BORDER=Color.rgb(229,231,235), BG=Color.rgb(247,247,248), GREEN=Color.rgb(22,101,52), RED=Color.rgb(185,28,28);
  DB db; LinearLayout body,nav; int tab=0; final NumberFormat money=NumberFormat.getCurrencyInstance(new Locale("es","PE"));
  int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);} 
  TextView t(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
  GradientDrawable shape(int fill,int radius){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(radius));return g;}
  GradientDrawable bordered(){GradientDrawable g=shape(Color.WHITE,18);g.setStroke(dp(1),BORDER);return g;}
  LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(16),dp(16),dp(16),dp(16));l.setBackground(bordered());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(12));l.setLayoutParams(p);return l;}
  Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setBackground(shape(TEXT,14));b.setMinHeight(dp(50));return b;}

  @Override public void onCreate(Bundle b){super.onCreate(b);db=new DB(this);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(Color.WHITE);shell();dashboard();}
  void shell(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setBackgroundColor(Color.WHITE);nav.setPadding(dp(8),dp(6),dp(8),dp(8));root.addView(nav,new LinearLayout.LayoutParams(-1,dp(68)));setContentView(root);nav();}
  void nav(){nav.removeAllViews();String[] a={"⌂\nInicio","↕\nMovimientos","◉\nCategorías"};for(int i=0;i<3;i++){final int x=i;TextView v=t(a[i],12,i==tab?TEXT:MUTED,i==tab);v.setGravity(Gravity.CENTER);if(i==tab)v.setBackground(shape(Color.rgb(243,244,246),14));v.setOnClickListener(q->{tab=x;nav();if(x==0)dashboard();else if(x==1)movements();else categories();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1);p.setMargins(dp(3),0,dp(3),0);nav.addView(v,p);}}
  void page(String title,String sub){body.removeAllViews();body.setPadding(dp(16),dp(18),dp(16),dp(24));body.addView(t(title,26,TEXT,true));TextView s=t(sub,14,MUTED,false);s.setPadding(0,dp(4),0,dp(18));body.addView(s);}

  void dashboard(){tab=0;nav();page("Mi dinero","Resumen general de tus finanzas");Totals x=db.totals();LinearLayout bal=card();bal.addView(t("Saldo disponible",14,MUTED,false));TextView val=t(money.format(x.in-x.out),32,TEXT,true);val.setPadding(0,dp(8),0,0);bal.addView(val);body.addView(bal);
    LinearLayout row=new LinearLayout(this);LinearLayout ci=small("Entradas",money.format(x.in),GREEN),co=small("Salidas",money.format(x.out),RED);LinearLayout.LayoutParams pi=new LinearLayout.LayoutParams(0,-2,1);pi.setMargins(0,0,dp(6),dp(12));row.addView(ci,pi);LinearLayout.LayoutParams po=new LinearLayout.LayoutParams(0,-2,1);po.setMargins(dp(6),0,0,dp(12));row.addView(co,po);body.addView(row);
    Button add=btn("+  Registrar movimiento");add.setOnClickListener(v->movementDialog());LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(52));ap.setMargins(0,0,0,dp(16));body.addView(add,ap);
    LinearLayout graph=card();graph.addView(t("Entradas vs. salidas",18,TEXT,true));TextView gs=t("Acumulado general",13,MUTED,false);gs.setPadding(0,dp(2),0,dp(8));graph.addView(gs);graph.addView(new Bars(this,x.in,x.out),new LinearLayout.LayoutParams(-1,dp(180)));body.addView(graph);
    LinearLayout pc=card();pc.addView(t("Por categoría",18,TEXT,true));ArrayList<CT> list=db.categoryTotals();if(list.isEmpty())pc.addView(t("Sin datos",14,MUTED,false));else pc.addView(new CatBars(this,list),new LinearLayout.LayoutParams(-1,dp(Math.max(130,list.size()*70))));body.addView(pc);
    LinearLayout recent=card();recent.addView(t("Últimos movimientos",18,TEXT,true));ArrayList<Move> ms=db.moves(5);if(ms.isEmpty()){TextView e=t("Aún no registraste movimientos.",14,MUTED,false);e.setPadding(0,dp(12),0,0);recent.addView(e);}else for(Move m:ms)recent.addView(moveRow(m));body.addView(recent);
  }
  LinearLayout small(String a,String b,int c){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(14),dp(14),dp(14),dp(14));l.setBackground(bordered());l.addView(t(a,13,MUTED,false));TextView v=t(b,18,c,true);v.setPadding(0,dp(8),0,0);l.addView(v);return l;}

  void movements(){tab=1;nav();page("Movimientos","Historial de entradas y salidas");Button add=btn("+  Nuevo movimiento");add.setOnClickListener(v->movementDialog());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(0,0,0,dp(16));body.addView(add,p);ArrayList<Move> ms=db.moves(500);if(ms.isEmpty()){LinearLayout c=card();c.addView(t("No hay movimientos registrados.",15,MUTED,false));body.addView(c);}for(Move m:ms){LinearLayout c=card();c.setPadding(dp(12),dp(4),dp(12),dp(4));c.addView(moveRow(m));c.setOnLongClickListener(v->{new AlertDialog.Builder(this).setTitle("Eliminar movimiento").setMessage("¿Eliminar "+money.format(m.amount)+"?").setNegativeButton("Cancelar",null).setPositiveButton("Eliminar",(d,w)->{db.deleteMove(m.id);movements();}).show();return true;});body.addView(c);}}
  View moveRow(Move m){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(0,dp(10),0,dp(10));TextView ic=t(m.icon,24,TEXT,false);ic.setGravity(Gravity.CENTER);r.addView(ic,new LinearLayout.LayoutParams(dp(44),dp(44)));LinearLayout mid=new LinearLayout(this);mid.setOrientation(LinearLayout.VERTICAL);mid.addView(t(m.cat,15,TEXT,true));mid.addView(t(m.date+(m.note.isEmpty()?"":" · "+m.note),12,MUTED,false));r.addView(mid,new LinearLayout.LayoutParams(0,-2,1));boolean in=m.type.equals("IN");TextView amt=t((in?"+ ":"- ")+money.format(m.amount),15,in?GREEN:RED,true);amt.setGravity(Gravity.END);r.addView(amt);return r;}

  void categories(){tab=2;nav();page("Categorías","Crea tus propias categorías e iconos");Button add=btn("+  Crear categoría");add.setOnClickListener(v->categoryDialog());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(0,0,0,dp(16));body.addView(add,p);for(Category c:db.categories()){LinearLayout box=card();box.setOrientation(LinearLayout.HORIZONTAL);box.setGravity(Gravity.CENTER_VERTICAL);TextView ic=t(c.icon,26,TEXT,false);ic.setGravity(Gravity.CENTER);box.addView(ic,new LinearLayout.LayoutParams(dp(52),dp(52)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(t(c.name,16,TEXT,true));CT ct=db.categoryTotal(c.id);tx.addView(t("Entradas "+money.format(ct.in)+" · Salidas "+money.format(ct.out),12,MUTED,false));box.addView(tx,new LinearLayout.LayoutParams(0,-2,1));box.addView(t("Mantén pulsado",11,MUTED,false));box.setOnLongClickListener(v->{if(db.used(c.id)){Toast.makeText(this,"La categoría tiene movimientos",Toast.LENGTH_SHORT).show();}else new AlertDialog.Builder(this).setTitle("Eliminar categoría").setMessage("¿Eliminar “"+c.name+"”?").setNegativeButton("Cancelar",null).setPositiveButton("Eliminar",(d,w)->{db.deleteCategory(c.id);categories();}).show();return true;});body.addView(box);}}

  void categoryDialog(){String[] icons={"🍽️","🚗","🏠","❤️","🛍️","💼","📦","🎓","🎉","✈️","📱","💡","🐾","🎁","💰","🧾"};LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(20),0,dp(20),0);EditText n=new EditText(this);n.setHint("Nombre de categoría");n.setSingleLine();f.addView(n,new LinearLayout.LayoutParams(-1,dp(58)));Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,icons));f.addView(sp,new LinearLayout.LayoutParams(-1,dp(58)));AlertDialog d=new AlertDialog.Builder(this).setTitle("Nueva categoría").setView(f).setNegativeButton("Cancelar",null).setPositiveButton("Crear",null).create();d.setOnShowListener(q->d.getButton(-1).setOnClickListener(v->{String name=n.getText().toString().trim();if(name.length()<2){n.setError("Escribe un nombre");return;}db.addCategory(name,(String)sp.getSelectedItem());d.dismiss();categories();}));d.show();}

  void movementDialog(){ArrayList<Category> cats=db.categories();if(cats.isEmpty()){Toast.makeText(this,"Primero crea una categoría",Toast.LENGTH_SHORT).show();categories();return;}LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(20),0,dp(20),0);f.addView(t("Tipo de movimiento",13,MUTED,true));RadioGroup rg=new RadioGroup(this);rg.setOrientation(RadioGroup.HORIZONTAL);RadioButton ri=new RadioButton(this);ri.setId(101);ri.setText("Entrada");RadioButton ro=new RadioButton(this);ro.setId(102);ro.setText("Salida");ro.setChecked(true);rg.addView(ri,new RadioGroup.LayoutParams(0,-2,1));rg.addView(ro,new RadioGroup.LayoutParams(0,-2,1));f.addView(rg);EditText amount=new EditText(this);amount.setHint("Monto, ej. 35.50");amount.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL);f.addView(amount,new LinearLayout.LayoutParams(-1,dp(58)));Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,cats));f.addView(sp,new LinearLayout.LayoutParams(-1,dp(56)));final String[] date={new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date())};Button dateBtn=new Button(this);dateBtn.setAllCaps(false);dateBtn.setText("Fecha: "+date[0]);dateBtn.setOnClickListener(v->{Calendar c=Calendar.getInstance();new DatePickerDialog(this,(vv,y,m,d)->{date[0]=String.format(Locale.US,"%04d-%02d-%02d",y,m+1,d);dateBtn.setText("Fecha: "+date[0]);},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show();});f.addView(dateBtn,new LinearLayout.LayoutParams(-1,dp(52)));EditText note=new EditText(this);note.setHint("Nota (opcional)");note.setSingleLine();f.addView(note,new LinearLayout.LayoutParams(-1,dp(58)));AlertDialog d=new AlertDialog.Builder(this).setTitle("Nuevo movimiento").setView(f).setNegativeButton("Cancelar",null).setPositiveButton("Guardar",null).create();d.setOnShowListener(q->d.getButton(-1).setOnClickListener(v->{double a;try{a=Double.parseDouble(amount.getText().toString().trim().replace(",","."));}catch(Exception e){amount.setError("Monto inválido");return;}if(a<=0){amount.setError("Debe ser mayor a 0");return;}Category c=(Category)sp.getSelectedItem();db.addMove(rg.getCheckedRadioButtonId()==101?"IN":"OUT",a,c.id,note.getText().toString().trim(),date[0]);d.dismiss();if(tab==1)movements();else dashboard();}));d.show();}

  static class Category{long id;String name,icon;Category(long i,String n,String c){id=i;name=n;icon=c;}public String toString(){return icon+"  "+name;}}
  static class Move{long id;String type,note,date,cat,icon;double amount;}
  static class Totals{double in,out;}
  static class CT{long id;String name,icon;double in,out;}

  static class DB extends SQLiteOpenHelper{
    DB(Context c){super(c,"control_gastos.db",null,1);}public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE categories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,icon TEXT NOT NULL)");d.execSQL("CREATE TABLE movements(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT NOT NULL,amount REAL NOT NULL,category_id INTEGER NOT NULL,note TEXT NOT NULL DEFAULT '',date TEXT NOT NULL)");String[][] s={{"Alimentación","🍽️"},{"Transporte","🚗"},{"Hogar","🏠"},{"Salud","❤️"},{"Compras","🛍️"},{"Sueldo","💼"},{"Otros","📦"}};for(String[] x:s){ContentValues v=new ContentValues();v.put("name",x[0]);v.put("icon",x[1]);d.insert("categories",null,v);}}public void onUpgrade(SQLiteDatabase d,int o,int n){}
    void addCategory(String n,String i){ContentValues v=new ContentValues();v.put("name",n);v.put("icon",i);getWritableDatabase().insert("categories",null,v);}void deleteCategory(long id){getWritableDatabase().delete("categories","id=?",new String[]{""+id});}boolean used(long id){Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM movements WHERE category_id=?",new String[]{""+id});boolean r=c.moveToFirst()&&c.getLong(0)>0;c.close();return r;}
    ArrayList<Category> categories(){ArrayList<Category>a=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT id,name,icon FROM categories ORDER BY name",null);while(c.moveToNext())a.add(new Category(c.getLong(0),c.getString(1),c.getString(2)));c.close();return a;}
    void addMove(String type,double a,long id,String note,String date){ContentValues v=new ContentValues();v.put("type",type);v.put("amount",a);v.put("category_id",id);v.put("note",note);v.put("date",date);getWritableDatabase().insert("movements",null,v);}void deleteMove(long id){getWritableDatabase().delete("movements","id=?",new String[]{""+id});}
    Totals totals(){Totals t=new Totals();Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(SUM(CASE WHEN type='IN' THEN amount ELSE 0 END),0),COALESCE(SUM(CASE WHEN type='OUT' THEN amount ELSE 0 END),0) FROM movements",null);if(c.moveToFirst()){t.in=c.getDouble(0);t.out=c.getDouble(1);}c.close();return t;}
    ArrayList<Move> moves(int n){ArrayList<Move>a=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT m.id,m.type,m.amount,m.note,m.date,c.name,c.icon FROM movements m JOIN categories c ON c.id=m.category_id ORDER BY m.date DESC,m.id DESC LIMIT "+Math.max(1,n),null);while(c.moveToNext()){Move m=new Move();m.id=c.getLong(0);m.type=c.getString(1);m.amount=c.getDouble(2);m.note=c.getString(3);m.date=c.getString(4);m.cat=c.getString(5);m.icon=c.getString(6);a.add(m);}c.close();return a;}
    ArrayList<CT> categoryTotals(){ArrayList<CT>a=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT c.id,c.name,c.icon,COALESCE(SUM(CASE WHEN m.type='IN' THEN m.amount ELSE 0 END),0),COALESCE(SUM(CASE WHEN m.type='OUT' THEN m.amount ELSE 0 END),0) FROM categories c LEFT JOIN movements m ON m.category_id=c.id GROUP BY c.id,c.name,c.icon ORDER BY c.name",null);while(c.moveToNext()){CT x=new CT();x.id=c.getLong(0);x.name=c.getString(1);x.icon=c.getString(2);x.in=c.getDouble(3);x.out=c.getDouble(4);a.add(x);}c.close();return a;}
    CT categoryTotal(long id){CT x=new CT();Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(SUM(CASE WHEN type='IN' THEN amount ELSE 0 END),0),COALESCE(SUM(CASE WHEN type='OUT' THEN amount ELSE 0 END),0) FROM movements WHERE category_id=?",new String[]{""+id});if(c.moveToFirst()){x.in=c.getDouble(0);x.out=c.getDouble(1);}c.close();return x;}
  }

  static class Bars extends View{Paint p=new Paint(1);double a,b;NumberFormat nf=NumberFormat.getCurrencyInstance(new Locale("es","PE"));Bars(Context c,double i,double o){super(c);a=i;b=o;}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight(),base=h-38;double mx=Math.max(1,Math.max(a,b));double[] vals={a,b};int[] cols={GREEN,RED};String[] names={"Entradas","Salidas"};for(int i=0;i<2;i++){float x=w*(i==0?.30f:.70f),bw=Math.min(84,w*.20f),bh=(float)((base-42)*(vals[i]/mx));p.setColor(Color.rgb(229,231,235));c.drawRoundRect(x-bw/2,30,x+bw/2,base,16,16,p);p.setColor(cols[i]);c.drawRoundRect(x-bw/2,base-bh,x+bw/2,base,16,16,p);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(26);p.setColor(TEXT);c.drawText(nf.format(vals[i]),x,22,p);p.setTextSize(24);p.setColor(MUTED);c.drawText(names[i],x,h-8,p);}}}
  static class CatBars extends View{Paint p=new Paint(1);ArrayList<CT>d;NumberFormat nf=NumberFormat.getCurrencyInstance(new Locale("es","PE"));CatBars(Context c,ArrayList<CT>x){super(c);d=x;}protected void onDraw(Canvas c){float w=getWidth(),y=24;double mx=1;for(CT x:d)mx=Math.max(mx,Math.max(x.in,x.out));for(CT x:d){p.setTextAlign(Paint.Align.LEFT);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(26);p.setColor(TEXT);c.drawText(x.icon+"  "+x.name,4,y,p);float left=Math.min(125,w*.35f),right=w-6,bw=right-left;y+=12;p.setColor(Color.rgb(220,252,231));c.drawRoundRect(left,y,right,y+10,5,5,p);p.setColor(GREEN);c.drawRoundRect(left,y,left+(float)(bw*x.in/mx),y+10,5,5,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(19);p.setColor(MUTED);c.drawText("E "+nf.format(x.in),4,y+10,p);y+=22;p.setColor(Color.rgb(254,226,226));c.drawRoundRect(left,y,right,y+10,5,5,p);p.setColor(RED);c.drawRoundRect(left,y,left+(float)(bw*x.out/mx),y+10,5,5,p);p.setColor(MUTED);c.drawText("S "+nf.format(x.out),4,y+10,p);y+=36;}}}
}
